name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ https://gist.github.com/sleepyhood/ }}
          TIMEZONE: Asia/Seoul
